version: '3.8'

services:
  home-library:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - postgresdb
    environment:
      PORT: ${PORT}
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public"    
    networks:
      - home-library-network

  postgresdb:
    build: ./postgres/
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - home-library-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    command:
      [
        'postgres',
        '-c',
        'logging_collector=on',
        '-c',
        'log_directory=./logs',
        '-c',
        'log_filename=postgresql.log',
        '-c',
        'log_statement=all',
      ]

networks:
  home-library-network:
    driver: bridge

volumes:
  pgdata:
